#!/bin/bash

_bfg_argcomplete() {
    local IFS=$'\013'
    local SUPPRESS_SPACE=0
    local cur prev opts
    if compopt +o nospace 2> /dev/null; then
        SUPPRESS_SPACE=1
    fi

    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="--clone --find-big-files --remove-big-files --push --help"

    if [[ ${prev} == "--find-big-files" || ${prev} == "--remove-big-files" ]]; then
        COMPREPLY=( $(compgen -W "1M 5M 10M 50M 100M 500M 1G" -- ${cur}) )
    elif [[ ${cur} == -* ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    else
        COMPREPLY=( $(compgen -f ${cur}) )
    fi

    if [[ $? != 0 ]]; then
        unset COMPREPLY
    elif [[ $SUPPRESS_SPACE == 1 ]] && [[ "$COMPREPLY" =~ [=/:]$ ]]; then
        compopt -o nospace
    fi
}

complete -o nospace -o default -F _bfg_argcomplete "bfg"
